name: Jira Add Comment
description: Add a comment to an issue
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to be commented on
    required: true
  comment:
    description: Comment
    required: true
  allow-repeats:
    description: "Allow messages to be repeated."
    required: false
    default: "false"
runs:
  using: 'node12'
  main: './dist/index.js'
