on: push

name: Test comment

jobs:
  test-comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create new issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: COM
        issuetype: Task
        summary: Issue for comment ${{ github.repository }}
        description: Compare branch|${{ github.event.compare }} # https://developer.github.com/v3/activity/events/types/#webhook-payload-example-31

    - name: Comment on issue
      uses: ./
      with:
        issue: ${{ steps.create.outputs.issue }}
        comment: Test comment ${{ github.event.compare }}
